FROM node:19-slim AS builder

ARG ROOT_PASS
ARG USERNAME
ARG GROUP
ARG PROJECT_ROOT_ABSPATH
ARG REPO_RELPATH
ARG APP_RELPATH
ARG NEXT_PUBLIC_WEB_APP_URL
ARG NEXT_PUBLIC_API_V1_URL
ARG PROTO_REPO_RELPATH

ARG REPO_ABSPATH="$PROJECT_ROOT_ABSPATH/$REPO_RELPATH"
ARG PROTO_REPO_ABSPATH="$PROJECT_ROOT_ABSPATH/$PROTO_REPO_RELPATH"
ARG APP_ABSPATH="$REPO_ABSPATH/$APP_RELPATH"

WORKDIR $PROJECT_ROOT_ABSPATH
COPY $REPO_REL_PATH $REPO_REL_PATH
COPY proto proto
RUN chown -R $CONTAINER_USERNAME:$CONTAINER_GROUP $PROJECT_ROOT_ABSPATH

WORKDIR $REPO_ABSPATH
RUN yarn --immutable
RUN yarn plugin import workspace-tools
RUN cd packages/openapi && yarn generate:all && cd ../..

WORKDIR $PROTO_REPO_ABSPATH
RUN yarn --immutable
RUN yarn generate:frontend

WORKDIR $REPO_ABSPATH
RUN yarn build --filter=web

FROM node:19-slim AS runner

ARG ROOT_PASS
ARG USERNAME
ARG GROUP
ARG PROJECT_ROOT_ABSPATH
ARG REPO_RELPATH
ARG APP_RELPATH

ARG REPO_ABSPATH="$PROJECT_ROOT_ABSPATH/$REPO_RELPATH"
ARG APP_ABSPATH="$REPO_ABSPATH/$APP_RELPATH"
ARG PACKAGES_ABSPATH=$REPO_ABSPATH/packages

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'

RUN apt update

WORKDIR $REPO_ABSPATH
COPY --from=builder "$REPO_ABSPATH/yarn.lock" yarn.lock
COPY --from=builder "$REPO_ABSPATH/.yarnrc.yml" .yarnrc.yml
COPY --from=builder "$REPO_ABSPATH/package.json" package.json
COPY --from=builder "$REPO_ABSPATH/turbo.json" turbo.json
COPY --from=builder "$REPO_ABSPATH/.yarn" .yarn
RUN ls -al $REPO_ABSPATH

WORKDIR $APP_ABSPATH
COPY --from=builder "$APP_ABSPATH/dist" dist
COPY --from=builder "$APP_ABSPATH/scripts" scripts
COPY --from=builder "$APP_ABSPATH/package.json" package.json
COPY --from=builder "$APP_ABSPATH/next.config.js" next.config.js
RUN ls -al $APP_ABSPATH

WORKDIR $PACKAGES_ABSPATH/app
COPY --from=builder "$PACKAGES_ABSPATH/app/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/i18n
COPY --from=builder "$PACKAGES_ABSPATH/i18n/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/store
COPY --from=builder "$PACKAGES_ABSPATH/store/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/tsconfig
COPY --from=builder "$PACKAGES_ABSPATH/tsconfig/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/ui
COPY --from=builder "$PACKAGES_ABSPATH/ui/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/web3
COPY --from=builder "$PACKAGES_ABSPATH/web3/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/openapi
COPY --from=builder "$PACKAGES_ABSPATH/openapi/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/api
COPY --from=builder "$PACKAGES_ABSPATH/api/package.json" package.json
RUN ls -al 

WORKDIR $PACKAGES_ABSPATH/grpc
COPY --from=builder "$PACKAGES_ABSPATH/grpc/package.json" package.json
RUN ls -al 

WORKDIR $APP_ABSPATH
RUN yarn workspaces focus --production -A

WORKDIR $REPO_ABSPATH
RUN rm -rf .yarn/cache

WORKDIR $APP_ABSPATH
USER $USERNAME
ENTRYPOINT scripts/entrypoint.sh
