version: "3.9"

services:
  nextjs-grpc-frontend:
    # image: utkusarioglu/react-native-android-devcontainer:1.0.17
    image: utkusarioglu/react-native-android-devcontainer:tag-unavailable
    environment:
      ANDROID_TARGET_DEVICE: android-host:58526
    extra_hosts:
      android-host: host-gateway
      ms.ms: host-gateway
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: ..
        target: /utkusarioglu-com/projects/nextjs-grpc/frontend
      - type: bind
        source: ../../proto
        target: /utkusarioglu-com/projects/nextjs-grpc/proto
