name: Build Android App
on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    paths:
      - apps/**
      - packages/**
      - .github/workflows/build-web.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO_RELPATH: frontend
  APP_RELPATH: apps/android
  APK_RELEASE_DIR_RELPATH: android/app/build/outputs/apk/release
  APK_RELEASE_FILENAME: app-release.apk
    
jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    container:
      image: utkusarioglu/react-native-android-devcontainer:tag-unavailable
      options: --user=0:0
      # image: utkusarioglu/react-native-android-devcontainer:1.0.17
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: ${{ env.REPO_RELPATH }}

      - name: Install monorepo dependencies
        working-directory: ${{ env.REPO_RELPATH }}
        run: |
          ls -al
          cat package.json
          yarn

      - name: Build android
        working-directory: ${{ env.REPO_RELPATH }}/${{ env.APP_RELPATH }}
        run: |
          yarn build-release

      - name: Create variables
        id: variables
        run: |
          date_string="$(date +'%Y-%m-%dT-%H-%M-%S')"
          echo "date_string=$date_string" >> $GITHUB_OUTPUT

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_TOKEN }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: "app-release-${{ steps.variables.outputs.date_string }}.apk"
          filename: ${{ env.REPO_RELPATH }}/${{ env.APP_RELPATH }}/${{ env.APK_RELEASE_DIR_RELPATH }}/${{ env.APK_RELEASE_FILENAME }}
          overwrite: "false"

      - name: Builds as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: utkusarioglu-android-build
          path: ${{ env.REPO_RELPATH }}/${{ env.APP_RELPATH }}/${{ env.APK_RELEASE_DIR_RELPATH }}
