name: Build Android App

on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    paths:
      - apps/**
      - packages/**
      - .github/workflows/build-android.yml
      - .github/workflows/build-android.wfc.yml
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    name: build-android
    secrets: inherit
    uses: ./.github/workflows/build-android.wfc.yml
