name: Build and test

on:
  workflow_call:
  # push:
  #   tags:
  #     - "**.**.**"
  #     - "experiment/**/**/**"
  #   paths:
  #     - apps/**
  #     - packages/**
  #     - .github/workflows/build-web.yml
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - edited
  #     - synchronize
  #   branches:
  #     - main
  # workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android:
    name: build-android
    secrets: inherit
    uses: ./.github/workflows/android.build.wfc.yml

  build-web:
    name: build-and-push
    uses: ./.github/workflows/web.build.wfc.yml
    secrets: inherit
    with:
      ref: ${{ github.ref_name }}

  test-web-server-endpoints:
    name: test-web-server-endpoints
    uses: ./.github/workflows/web-server-endpoints.test.wfc.yml
    secrets: inherit
    needs:
      - build-web
    with:
      ref: ${{ github.ref_name }}

  create-variables:
    name: create-variables
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.create-variables.outputs.image_tag }}
    steps:
      - id: create-variables
        run: |
          repo_tag="${{ github.ref_name }}"
          image_tag="${repo_tag//\//-}"
          echo "image tag is: $image_tag"
          echo "image_tag=$image_tag" >> "$GITHUB_OUTPUT"

  test-k8s-integration:
    name: infra-test-web
    uses: utkusarioglu/nextjs-grpc-infra/.github/workflows/k3d-dev-local.test.wfc.yml@experiment/test/workflow-calls
    secrets: inherit
    needs:
      - test-web-server-endpoints
      - create-variables
    with:
      frontendRef: ${{ github.ref_name }}
      infraRef: experiment/test/workflow-calls

      webServerImageTag: ${{ needs.create-variables.outputs.image_tag }}
      # msImageTag: "bbb"
