name: Integration Test K3d Local
  
on:
  # push:
  #   tags:
  #     - "**.**.**"
  #     - "experiment/**/**/**"
  #   paths:
  #     - apps/**
  #     - packages/**
  #     - .github/workflows/integration-test-k3d.yml
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  infra-test-web:
    name: infra-test-web
    uses: utkusarioglu/nextjs-grpc-infra/.github/workflows/test-k3d-dev-local-call.yml@main
    secrets: inherit
    with:
      frontend: ${{ github.head_ref }}
