name: PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push:
    uses: ./.github/workflows/build-test-push.wfc.yml
    secrets: inherit
    with:
      frontendRef: ${{ github.head_ref }}
      infraRef: experiment/test/workflow-calls
      # msImageTag: 
