name: Push

on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    paths:
      - apps/**
      - packages/**
      - .github/workflows/build-web.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push:
    uses: ./.github/workflows/build-test-push.wfc.yml
    secrets: inherit
    with:
      frontendRef: ${{ github.ref_name }}
      infraRef: experiment/test/workflow-calls
      # msImageTag: 
