name: Push

on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    paths:
      - apps/**
      - packages/**
      - .github/workflows/build-web.yml
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    secrets: inherit
    uses: ./.github/workflows/build-and-test.yml
